//===- ECSLOps.cpp - ECSL dialect operations ------------------------------===//
//
// Implements the ECSL dialect operation classes (generated by TableGen).
//
//===----------------------------------------------------------------------===//

#include "ecsl/IR/ECSLOps.h"

#include "ecsl/IR/ECSLDialect.h" // IWYU pragma: keep (used by generated .inc)

#define GET_OP_CLASSES
#include "ecsl/IR/ECSLOps.cpp.inc"
